Fix link to point to active Git repo
stolostron/gatekeeper-operator pull request #107
Opened 2024-09-26 15:28 UTC by mprahl

2024-09-26 15:28 UTC, dhaiducek approved these changes
Thanks! I was just trying to find this!

2024-09-26 15:30 UTC, dhaiducek requested changes
Actually, there's a "report issues" that points to the defunct upstream also.

2024-09-26 15:43 UTC, yiraeChristineKim approved these changes

2024-09-26 15:43 UTC, mprahl commented
> ...and while we're here, could you fix the badge links at the top of the README also?

@dhaiducek, I gave an inch and you took a mile :laughing: 

I just renamed the entire thing to be Stolostron, including the Go module.

2024-09-26 15:44 UTC, mprahl commented
/hold for reviews

2024-09-26 15:53 UTC, dhaiducek commented
> I just renamed the entire thing to be Stolostron, including the Go module.

Let's not go crazy here--I asked for 6 additional lines and you made it 50 😂 
I think doing a rename on it all makes sense though--in the unlikely event the operator ever gets upstreamed, it's going directly to OPA, not back to the gatekeeper org.

2024-09-26 15:53 UTC, dhaiducek approved these changes

2024-09-26 16:01 UTC, mprahl commented
/unhold

2024-09-26 16:01 UTC, mprahl commented
/override "SonarCloud Code Analysis"

2024-09-26 16:06 UTC, merged

2024-10-03 14:43 UTC, dhaiducek commented
/cherry-pick release-3.15

2024-10-03 14:43 UTC, dhaiducek commented
/cherry-pick release-3.14