Increase memory limit for ROSA/HCP env
stolostron/gatekeeper-operator pull request #55
Opened 2024-02-01 21:16 UTC by yiraeChristineKim

2024-02-01 22:37 UTC, dhaiducek requested changes
Thanks for the quick update! Looks good--I have a couple questions/comments.

2024-02-01 22:37 UTC, dhaiducek commented on controllers/gatekeeper_controller_test.go
> +func assertResources(g *WithT, obj *unstructured.Unstructured, expected *corev1.ResourceRequirements, isAudit bool) {
The `isAudit` boolean is unnecessary--you should just pass in the `expected` for all audit tests and leave the `assertResources` function as it is, right?

2024-02-01 22:37 UTC, dhaiducek commented on config/gatekeeper/kustomization.yaml
> +    name: gatekeeper-audit
All the patches above this one target the `gatekeeper-audit` Deployment. Can we consolidate them into a single `patch` array?

2024-02-02 13:30 UTC, dhaiducek requested changes
Looks way cleaner--thanks!

Please add the Jira issue to the commit message, and this should be good to go!

2024-02-02 13:30 UTC, dhaiducek commented on config/gatekeeper/kustomization.yaml
>  # Set a CPU limit
```suggestion
# Set a CPU limit
# Increase default Memory limit
```

2024-02-02 14:00 UTC, dhaiducek approved these changes

2024-02-02 14:00 UTC, dhaiducek commented
/cherry-pick release-3.11

2024-02-02 14:02 UTC, yiraeChristineKim commented
@dhaiducek  ooooh!! Thanks for cherrypicking

2024-02-02 14:05 UTC, merged