Update Gatekeeper CRD descriptions
stolostron/gatekeeper-operator pull request #67
Opened 2024-04-01 14:41 UTC by dhaiducek

This represents a major update to the descriptions and reorganization of the `*_types.go` file, placing dependent structs higher in the file (or closer to structs that require them where relevant). I couldn't find where `status` was even used, so I've gutted it. I can revert that if there are concerns, but it seemed relatively safe since the operator should be the only thing populating it. I also made an effort to link to the upstream Gatekeeper docs wherever possible, which I think will go a long way toward enabling serviceability and helpfulness of the operator configuration.

ref: https://issues.redhat.com/browse/ACM-8992

2024-04-02 14:38 UTC, JustinKuli submitted a review, later dismissed
/hold if anyone else wants to check, but it looks good to me!

2024-04-02 16:38 UTC, yiraeChristineKim approved these changes
Great!!

2024-04-02 18:52 UTC, dockerymick requested changes

2024-04-02 18:52 UTC, dockerymick commented on bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
> +        webhooks. (See https://github.com/open-policy-agent/gatekeeper)
```suggestion
    - description: Gatekeeper is the schema for the gatekeepers API. Gatekeeper contains
        configurations for the Gatekeeper operator, which deploys Open Policy Agent
        Gatekeeper, a policy engine that enforces policies through admission controller
        webhooks. See https://github.com/open-policy-agent/gatekeeper.
```

2024-04-02 18:52 UTC, dockerymick commented on bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
> +          deployment Pods. (See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/)
```suggestion
      - description: Affinity is a node affinity specification to add to the Gatekeeper
          deployment Pods. See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/.
```

2024-04-02 18:52 UTC, dockerymick commented on bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
> +          function. (See https://open-policy-agent.github.io/gatekeeper/website/docs/audit)
```suggestion
      - description: Audit specifies the configuration for the Gatekeeper auditing
          function. See https://open-policy-agent.github.io/gatekeeper/website/docs/audit.
```

2024-04-02 18:52 UTC, dockerymick commented on bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
> +          webhook is enabled. Defaults to Enabled. (See https://open-policy-agent.github.io/gatekeeper/website/docs/mutation)
```suggestion
          webhook is enabled. The default value is Enabled. See https://open-policy-agent.github.io/gatekeeper/website/docs/mutation.
```

2024-04-02 18:52 UTC, dockerymick commented on bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
> +          deployment Pods. (See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/)
```suggestion
      - description: NodeSelector is a map of node selectors to add to the Gatekeeper
          deployment Pods. See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/.
```

2024-04-02 18:52 UTC, dockerymick commented on bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
> +          deployment Pods. (See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
```suggestion
      - description: Tolerations is an array of tolerations to add to the Gatekeeper
          deployment Pods. See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/.
```

2024-04-02 18:52 UTC, dockerymick commented on bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
> +          admission webhook is enabled. Defaults to Enabled.
```suggestion
      - description: ValidatingWebhook specifies whether the Gatekeeper validating
          admission webhook is enabled. The default value is Enabled.
```

2024-04-02 18:52 UTC, dockerymick commented on config/manifests/bases/gatekeeper-operator.clusterserviceversion.yaml
> +    - description: Gatekeeper is the Schema for the gatekeepers API. Gatekeeper contains
Seems like these are similar descriptions from the `operator.gatekeeper.sh_gatekeeperrs.yaml. 

If that is accurate, I suggestion similar feedback

2024-04-02 21:21 UTC, mprahl commented on api/v1alpha1/gatekeeper_types.go
> +	// AuditInterval configures how often audit is run on the cluster. The default value is 60s.
```suggestion
	// AuditInterval configures how often an audit is run on the cluster. The default value is 60s.
```

2024-04-02 21:23 UTC, mprahl commented on api/v1alpha1/gatekeeper_types.go
> +	// LogMutations enables logging of mutation events and errors. The default value is Disabled.
```suggestion
	// LogMutations enables the logging of mutation events and errors. The default value is Disabled.
```

2024-04-02 21:25 UTC, mprahl commented on api/v1alpha1/gatekeeper_types.go
> +	// be appended to the existing Config spec.match.
It doesn't actually append it. It just appends to the default matches.
```suggestion
	// be set on the existing Config spec.match.
```

2024-04-03 13:03 UTC, mprahl approved these changes
Nice work!

2024-04-03 17:11 UTC, dockerymick requested changes
I realize that i didn't review another YAML file

2024-04-03 17:11 UTC, dockerymick commented on config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml
> +                      See https://open-policy-agent.github.io/gatekeeper/website/docs/customize-startup/#alpha-emit-admission-and-audit-events.
made a similar suggestion earlier.

2024-04-03 20:11 UTC, mprahl approved these changes

2024-04-03 20:19 UTC, dhaiducek commented
/unhold

2024-04-03 20:20 UTC, dhaiducek commented
Thanks for all the reviews, everyone! 😄

2024-04-03 20:24 UTC, merged