Fix secret name for openshift mode
stolostron/gatekeeper-operator pull request #80
Opened 2024-05-01 18:02 UTC by yiraeChristineKim

Upgrading the gatekeeper causes cert-issue due to the fact that the same secret name has been created by the service-ca already 
Ref: https://issues.redhat.com/browse/ACM-10859
Signed-off-by: yiraeChristineKim <yikim@redhat.com>

2024-05-02 14:29 UTC, mprahl commented on controllers/gatekeeper_controller.go
> +		return errors.Wrapf(err, "Failed to set --disable-cert-rotation for the OpenShift")
```suggestion
		return errors.Wrapf(err, "Failed to set --disable-cert-rotation for OpenShift")
```

2024-05-02 14:29 UTC, mprahl commented on controllers/gatekeeper_controller.go
> +		return errors.Wrapf(err, "Failed to set the secret name for the OpenShift")
```suggestion
		return errors.Wrapf(err, "Failed to set the secret name for OpenShift")
```

2024-05-02 14:29 UTC, mprahl commented on controllers/gatekeeper_controller.go
> +		return errors.Wrapf(err, "Failed to set secretName for the OpenShift")
```suggestion
		return errors.Wrapf(err, "Failed to set the certificate volume mount for OpenShift")
```

2024-05-02 14:30 UTC, mprahl commented on controllers/gatekeeper_controller.go
> +		return errors.Wrapf(err, "Failed to set the volumes with the openshift secretName for the OpenShift")
```suggestion
		return errors.Wrapf(err, "Failed to set the certificate volume mount for OpenShift")
```

2024-05-02 14:31 UTC, mprahl commented
@yiraeChristineKim this looks good to me after the log messages are fixed.

2024-05-02 15:04 UTC, dhaiducek commented on test/e2e/gatekeeper_controller_test.go
> +		const openshiftSecretName = "gatekeeper-webhook-server-cert-ocp"
Why not use `controller.OpenshiftSecretName` here, since it's a published variable?

2024-05-02 16:52 UTC, dhaiducek requested changes
I think this PR should be in `main` and _then_ cherry-picked to release-3.14? (You should be able to edit the target branch.)

2024-05-03 13:41 UTC, yiraeChristineKim commented
> I think this PR should be in `main` and _then_ cherry-picked to release-3.14? (You should be able to edit the target branch.)

Great!

2024-05-03 14:42 UTC, dhaiducek commented
Oops--it might need a rebase. Sorry about that--I was hoping it'd be more straightforward. 😞

2024-05-03 15:26 UTC, closed without merging